# Generated by Django 6.0.4 on 2026-05-03 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouresDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('pose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.yogapose')),
            ],
        ),
    ]
