# Generated by Django 6.0.4 on 2026-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('body_part', models.CharField(choices=[('neck', 'Neck'), ('knee', 'Knee'), ('back', 'Back')], max_length=10)),
                ('pain_level', models.CharField(choices=[('biginner', 'Biginner'), ('medium', 'Medium'), ('advanced', 'Advanced')], max_length=10)),
                ('instuctions', models.CharField(max_length=500)),
                ('benifits', models.CharField(max_length=500)),
                ('video', models.FileField(upload_to='yoga_images/')),
            ],
        ),
    ]
