# Generated by Django 6.0.4 on 2026-05-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogapose',
            name='video',
        ),
        migrations.AddField(
            model_name='yogapose',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yoga_images/'),
        ),
    ]
