# Generated by Django 6.0.4 on 2026-05-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_yogapose_video_yogapose_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogapose',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='yogapose',
            name='pain_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
    ]
